{
 "title": "Logger",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES FROM dev WITH KEY = \"location\""
   },
   { "name": "measurement", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Temp $location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"temp\") FROM /^$measurement$/ WHERE (\"location\" = /^$location$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Humid $location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "raspizero1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"humi\") FROM /^$measurement$/ WHERE (\"location\" = 'livingroom') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "humi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure $location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "press" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "IAQ $location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"iaq\") FROM /^$measurement$/ WHERE (\"location\" = 'livingroom') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "iaq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Indoor Air Quality",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean(\"iaq\") FROM /^$measurement$/ WHERE (\"location\" = 'livingroom') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "iaq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean(\"temp\") FROM /^$measurement$/ WHERE (\"location\" = 'livingroom') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "press" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "humi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ohm" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    },
    {
     "alias": "livingroom baseline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gasbaseline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "livingroom" }
     ]
    }
   ]
  },
  {
   "title": "Raw data from InfluxDB",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "measurement": "dev",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}